sylius_shop_order_comments_partial_comment_create:
    path: "/{orderId}/comments"
    methods: ["POST"]
    defaults:
        _controller: "brille24.order_comments_plugin.infrastructure.controller.ui.comment_form_action"

sylius_shop_order_comments_partial_comment_index:
    path: "/{number}/comments"
    methods: ["GET"]
    defaults:
        _controller: "sylius.controller.order_comment::indexAction"
        _sylius:
            paginate: false
            limit: false
            repository:
                method: findBy
                arguments:
                   - order: "expr:notFoundOnNull(service('sylius.repository.order').findOneByNumber($number))"
                   - createdAt: asc
            template: "@Brille24SyliusOrderCommentsPlugin/index.html.twig"
            isAdmin: false
